PortfolioBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne: 
        article:
            targetEntity: Article
            invercedBy: comments
            joinColumn: 
                name: article_id
                referencedColumnNnname: id
    lifecycleCallbacks: {  }
