PortfolioBundle\Entity\Portfolio:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\PortfolioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '111'
        description:
            type: string
            length: 255
            nullable: true
        thumbneil:
            type: integer
            length: '22'
            nullable: true
        content:
            type: text
            nullable: true
        slug:
            type: string
            length: '155'
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdAt:
            type: datetime
            column: created_at
    oneToMany:
        fields:
            targetEntity: PortfolioMeta
            mappedBy: portfolio
        rating:
            targetEntity: Rating
            mappedBy: portfolio
    oneToOne:
        portfolio:
            targetEntity: Media
            inversedBy: thumbneil
            joinColumn:
                name: media_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
