services:
#    portfolio.example:
#        class: PortfolioBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    portfolio_article.article_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - PortfolioBundle\Entity\Article