<?php

namespace PortfolioBundle\Repository;

/**
 * ArticleMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
