<?php

namespace PortfolioBundle\Repository;

/**
 * PortfolioMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
