<?php

namespace PortfolioBundle\Repository;

/**
 * UserMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
